import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/common/providers/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { RootProvider } from 'fumadocs-ui/provider';
import { getLocale } from "next-intl/server";
import { ClerkProvider } from "@clerk/nextjs";
import localFont from "next/font/local";

const aeronaut = localFont({
  src: "./fonts/Aeronaut.woff2",
  variable: "--font-aeronaut",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <ClerkProvider>
      <html lang={locale} suppressHydrationWarning>
        <body
          className={`${aeronaut.variable} antialiased`}
        >
          <NextIntlClientProvider>
            <RootProvider>
              {children}
             </RootProvider>
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
